# Generated by Django 6.0.6 on 2026-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('heading_1', models.CharField(default='', max_length=500)),
                ('heading_1_content', models.CharField(default='', max_length=5000)),
                ('heading_2', models.CharField(default='', max_length=500)),
                ('heading_2_content', models.CharField(max_length=5000)),
                ('sub_heading', models.CharField(default='', max_length=500)),
                ('sub_heading_content', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
