# Generated by Django 6.0.6 on 2026-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
